version: '3.8'

services:
  api:
    build:
      context: .
      args:
        - PORT=3000
    ports:
      - '${PORT}:${PORT}'    
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: